### PR TITLE
Update economic_incentives.md

### PR DESCRIPTION
**Pull request by doctor-gonzo**
reasons > reason

### CODE REVIEW

**Comment by jackalyst** [comment]
Thank you for the edit here.

**Comment by doctorr-gonso0** [comment]
@doctor-gonzo i have a question

**Comment by jackalyst** [comment]
> @doctor-gonzo i have a question

Ask away

**Comment by doctorr-gonso0** [comment]
@jackalyst 
Doctor-g up there,  do you know his name?

**Comment by jackalyst** [comment]
> @jackalyst Doctor-g up there, do you know his name?

That's not my information to give out.

**Comment by doctorr-gonso0** [comment]
Well the reason I ask is bc I believe it's my husband. can you just confirm
or deny if his initials are a.g.? Or first name Anthony? Or last name
gonsolis? Anything? Or help me look him up by fullname? He's here if you'd
like him to confirm that this is ok.

Thank you for your time

**Pull request merged**
